### ISSUE TITLE
Boundname can not be used as ID1 for any UZT observation despite documentation.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1028]
**Describe the bug**

Run that attached model.

**Expected behavior**
Model runs to completion or ends with an error message that is consistent with the documentation.
Each of the observations in the UZT package uses a valid boundary name but all result in error messages.
For some of the observation types such as concentration, it might make sense to restrict the use of boundary names related to single cells.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
[UztOb.zip](https://github.com/MODFLOW-USGS/modflow6/files/9464491/UztOb.zip)

**Comment by langevin-usgs** [comment]
PR #1024 should fix these issues, but @rbwinst-usgs, I don't see any valid boundnames in your UZT input file.  This is what I see in `UztOb.Chem.ob_uzt`.

```
ptf @
etf %
%ReadArrays(UztOb.Chem.txt)%
# UZF6: Unsaturated-Zone Flow Package for MODFLOW 6 file created on 8/31/2022 by ModelMuse version 5.0.0.25.
# (and then modified by a parameter estimation program.)
BEGIN OPTIONS
    FLOW_PACKAGE_NAME UZF-1
    PRINT_INPUT
    SAVE_FLOWS
    CONCENTRATION FILEOUT UztOb.Chem.uzt_conc
    BUDGET FILEOUT UztOb.Chem.uzt_budget
    OBS6 FILEIN UztOb.Chem.ob_uzt
END OPTIONS

BEGIN PACKAGEDATA
# <uzfno> <strt> [<aux(naux)>] [<boundname>
       1  0.000000000000E+000 
       2  0.000000000000E+000 
       3  0.000000000000E+000 
       4  0.000000000000E+000 
       5  0.000000000000E+000 
       6  0.000000000000E+000 
       7  0.000000000000E+000 
       8  0.000000000000E+000 
       9  0.000000000000E+000 
      10  0.000000000000E+000 
      11  0.000000000000E+000 
      12  0.000000000000E+000 
      13  0.000000000000E+000 
      14  0.000000000000E+000 
      15  0.000000000000E+000 
      16  0.000000000000E+000 
      17  0.000000000000E+000 
      18  0.000000000000E+000 
      19  0.000000000000E+000 
      20  0.000000000000E+000 
      21  0.000000000000E+000 
      22  0.000000000000E+000 
      23  0.000000000000E+000 
      24  0.000000000000E+000 
      25  0.000000000000E+000 
END PACKAGEDATA
```

**Comment by rbwinst-usgs** [comment]
OK. I thought the boundname was the one from the UZF file and I forgot to implement boundname for UZT.

**Comment by rbwinst-usgs** [comment]
With boundnames defined in UZT, it still doesn't work.
[UztOb2.zip](https://github.com/MODFLOW-USGS/modflow6/files/9464697/UztOb2.zip)

**Comment by rbwinst-usgs** [comment]
It appears to work with the new nightly build.

**Comment by rbwinst-usgs** [comment]
Actually, it still fails with VERSION 6.4.0 release candidate 08/31/2022

**Comment by rbwinst-usgs** [comment]
It still isn't working with the Sept. 1 nightly build.
[UztOb3.zip](https://github.com/MODFLOW-USGS/modflow6/files/9473206/UztOb3.zip)

**Comment by langevin-usgs** [comment]
You have to add `BOUNDNAMES` to the options block so the program knows to read them.  Your problem works for me when I make this change.
