### ISSUE TITLE
PRT error: floating divide by zero in subcell ternary method

### ISSUE THREAD

**Issue by cneyens** [MODFLOW-USGS/modflow6#2179]
**Describe the bug**
We've had this error in several models with Voronoi DISV grids. It was quite difficult to consistently reproduce since I'm not sure what's causing this. 
When placing particles in a DISV model, sometimes, with some of the particles, the PRT model errors out, displaying following error:

![Image](https://github.com/user-attachments/assets/40aeb241-24e8-41ae-8ab0-b595a6a571a9)

**To reproduce**
I've attached a model of a well in uniform background flow in a zip file. Nine particles are evenly spaced along a line perpendicular to the flow direction, upstream of the well. In the PRP file, I've commented on the particles which cause an error for these specific model settings.

[prt_error.zip](https://github.com/user-attachments/files/18603730/prt_error.zip)

Nudging the particle starting location slightly may cause to model to run fine.

I've noticed that in some cases, using stricter solution criteria for the flow model (or adjusting the XT3D option), and thus reducing the flow balance error, will cause the PRT model to run fine (or other particles to give an error). The errors with PRT may still occur even with discrepancies < 0.1 %. With the current options however, a flow balance error of 0.0 % is achieved, but the PRT error persists.

**Expected behavior**
I expect the PRT model to run correctly, independent of the starting location of a particle in a cell and for moderate flow balance errors.

**Environment**
 - Windows 10
 - MODFLOW 6 6.6.0

**Comment by wpbonelli** [comment]
Hi @cneyens perhaps try the nightly build? We've fixed some FPEs since 6.6.0.

I will take a look at your model asap.

**Comment by cneyens** [comment]
@wpbonelli thanks for the tip. The error still persists with the latest build, but for different particles.

**Comment by wpbonelli** [comment]
We've reproduced it and will follow up when a fix is available. Thanks for reporting and sharing the model.

**Comment by wpbonelli** [comment]
@cneyens this should be fixed by #2183. When converting to relative vertical coords we didn't check the value actually fell in the unit interval. Values very slightly above or below broke some expectations further down and caused the crash.

**Comment by cneyens** [comment]
> [@cneyens](https://github.com/cneyens) this should be fixed by [#2183](https://github.com/MODFLOW-USGS/modflow6/pull/2183). When converting to relative vertical coords we didn't check the value actually fell in the unit interval. Values very slightly above or below broke some expectations further down and caused the crash.

Thanks @wpbonelli!
